import type { Lesson } from "@/lib/types"

export const lessons: Lesson[] = [
  // Original lesson
  {
    id: "1",
    slug: "juli-slide-alphabet",
    title: "Juli Slide - Spanish Alphabet",
    description:
      "Learn the Spanish alphabet through an engaging hip-hop song with proper pronunciation and cultural vocabulary.",
    videoUrl: null,
    worksheetUrl: "/worksheets/alphabet-juli-slide.pdf",
    audioUrl: "/audio/Juli-Slide-Alphabet.mp3",
    progress: 0,
    category: "Fundamentals",
    difficulty: "beginner",
    duration: "8 min",
    isNew: true,
    isFeatured: true,
    learningPoints: [
      "Master Spanish alphabet pronunciation",
      "Learn cultural and social justice vocabulary",
      "Practice letter recognition and spelling",
      "Understand Spanish phonetics",
    ],
    vocabularyWords: [
      "El alfabeto - The alphabet",
      "Las letras - The letters",
      "A (ah) - Abolicionista",
      "B (bay) - Bandera",
      "C (say) - Cooperar",
      "D (day) - Discapacidad",
      "E (ay) - Español",
      "F (ef-fay) - Feminista",
      "G (hey) - Gente",
      "H (a-chay) - Humanidad",
      "I (eee) - Imaginación",
      "J (hoe-tah) - Justicia",
      "K (ka) - Karma",
      "L (el-ay) - Liberación",
      "M (em-ay) - Migrante",
      "N (en-ay) - Naturalista",
      "Ñ (en-yay) - Niño",
      "O (oh) - Optimista",
      "P (pay) - Posible",
      "Q (coo) - Querido",
      "R (air-ray) - Revolución",
      "S (es-say) - Sexualidad",
      "T (teh) - Transgenero",
      "U (oo) - Unión",
      "V (bay) - Visible",
      "W (do-bleh bay) - Woke",
      "X (eh-keys) - Xenofobia",
      "Y (ih-gree-ay-gah) - Yo",
      "Z (say-tah) - Zapatista",
    ],
    thumbnail: "/spanish-alphabet-lesson.png",
  },

  // Add the alfabeto lesson
  {
    id: "41",
    slug: "alfabeto",
    title: "El Alfabeto (Spanish Alphabet)",
    description: "Master the Spanish alphabet with proper pronunciation and letter recognition.",
    videoUrl: "https://www.youtube.com/watch?v=uOQMDaWSn6c",
    worksheetUrl: "/worksheets/Alphabet-The-ABCDs-Worksheet.pdf",
    audioUrl: "/audio/Juli-Slide-Alphabet.mp3",
    progress: 0,
    category: "Fundamentals",
    learningPoints: [
      "Spanish alphabet pronunciation",
      "Letter recognition and spelling",
      "Difference between Spanish and English alphabet",
      "Special letters: Ñ, RR, LL",
    ],
    vocabularyWords: [
      "El alfabeto",
      "Las letras",
      "A (ah)",
      "B (bay)",
      "C (say)",
      "D (day)",
      "E (ay)",
      "F (ef-fay)",
      "G (hey)",
      "H (a-chay)",
      "I (eee)",
      "J (hoe-tah)",
      "K (ka)",
      "L (el-ay)",
      "M (em-ay)",
      "N (en-ay)",
      "Ñ (en-yay)",
      "O (oh)",
      "P (pay)",
      "Q (coo)",
      "R (air-ray)",
      "S (es-say)",
      "T (teh)",
      "U (oo)",
      "V (bay)",
      "W (do-bleh bay)",
      "X (eh-keys)",
      "Y (ih-gree-ay-gah)",
      "Z (say-tah)",
    ],
    thumbnail: "/spanish-alphabet-lesson.png",
  },

  // Juli Slide Alphabet lesson - this is the one causing the error
  {
    id: "14",
    slug: "juli-slide-alphabet",
    title: "Juli Slide (Alphabet)",
    description: "Learn the Spanish alphabet through a catchy hip hop song with rhythm and flow.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Juli-Slide-Alphabet.mp3",
    progress: 0,
    category: "Fundamentals",
    learningPoints: [
      "Spanish alphabet pronunciation",
      "Letter recognition",
      "Spelling in Spanish",
      "Cultural vocabulary with each letter",
    ],
    vocabularyWords: [
      "El alfabeto",
      "Las letras",
      "A (ah)",
      "B (bay)",
      "C (say)",
      "D (day)",
      "E (ay)",
      "F (ef-fay)",
      "G (hey)",
      "H (a-chay)",
      "I (eee)",
      "J (hoe-tah)",
      "K (ka)",
      "L (el-ay)",
      "M (em-ay)",
      "N (en-ay)",
      "Ñ (en-yay)",
      "O (oh)",
      "P (pay)",
      "Q (coo)",
      "R (air-ray)",
      "S (es-say)",
      "T (teh)",
      "U (oo)",
      "V (bay)",
      "W (do-bleh bay)",
      "X (eh-keys)",
      "Y (ih-gree-ay-gah)",
      "Z (say-tah)",
    ],
    thumbnail: "/spanish-alphabet-lesson.png",
  },

  // Un Día en La Vida lessons
  {
    id: "2",
    slug: "numbers-0-101",
    title: "Spanish Numbers 0-101",
    description:
      "Master counting in Spanish from zero to one hundred and one with hip-hop rhythm and memorable patterns.",
    videoUrl: "https://www.youtube.com/watch?v=iVkolTR98ew",
    worksheetUrl: "/worksheets/numbers-0-101.pdf",
    audioUrl: "/audio/lessons/numbers-0-101-song.mp3",
    progress: 0,
    category: "Numbers",
    difficulty: "beginner",
    duration: "12 min",
    isFeatured: true,
    learningPoints: [
      "Count from 0 to 101 in Spanish",
      "Understand number formation patterns",
      "Use numbers in practical situations",
      "Master pronunciation of complex numbers",
    ],
    vocabularyWords: [
      "Cero - Zero",
      "Uno - One",
      "Dos - Two",
      "Tres - Three",
      "Cuatro - Four",
      "Cinco - Five",
      "Seis - Six",
      "Siete - Seven",
      "Ocho - Eight",
      "Nueve - Nine",
      "Diez - Ten",
      "Veinte - Twenty",
      "Treinta - Thirty",
      "Cuarenta - Forty",
      "Cincuenta - Fifty",
      "Sesenta - Sixty",
      "Setenta - Seventy",
      "Ochenta - Eighty",
      "Noventa - Ninety",
      "Cien - One hundred",
      "Ciento uno - One hundred and one",
    ],
    thumbnail: "/spanish-numbers-lesson.png",
  },

  {
    id: "15",
    slug: "puff-lah",
    title: "Puff Lah",
    description: "A fun hip-hop song to help you learn essential Spanish vocabulary with rhythm.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Puff-Lah.mp3",
    progress: 0,
    category: "Vocabulary",
    learningPoints: ["Essential Spanish vocabulary", "Pronunciation practice", "Rhythm and flow in Spanish"],
    vocabularyWords: ["Hola", "Adiós", "Gracias", "Por favor", "Sí", "No", "Buenos días", "Buenas noches"],
  },
  {
    id: "16",
    slug: "i-look-good",
    title: "I Look Good (Me Parece Guapo)",
    description: "Learn appearance and description vocabulary in Spanish through music.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/I-Look-Good-Me-Parece-Guapo.mp3",
    progress: 0,
    category: "Descriptions",
    learningPoints: ["Appearance vocabulary", "Self-description in Spanish", "Using 'parecer' and related verbs"],
    vocabularyWords: [
      "Guapo/a",
      "Bonito/a",
      "Alto/a",
      "Bajo/a",
      "Delgado/a",
      "Gordo/a",
      "Fuerte",
      "Me parece",
      "Se ve",
    ],
  },
  {
    id: "17",
    slug: "the-docs-health",
    title: "The Docs (Health)",
    description: "Learn health and medical vocabulary in Spanish through engaging music.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/The-Docs-Health.mp3",
    progress: 0,
    category: "Health",
    learningPoints: ["Medical vocabulary in Spanish", "Describing symptoms", "Doctor's visit conversations"],
    vocabularyWords: [
      "El doctor/La doctora",
      "El hospital",
      "La enfermedad",
      "El dolor",
      "La medicina",
      "La receta",
      "La farmacia",
      "Enfermo/a",
      "Sano/a",
    ],
  },
  {
    id: "18",
    slug: "spa-nish-travel",
    title: "Spa Nish (Travel)",
    description: "Essential Spanish vocabulary for travelers through catchy hip-hop beats.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Spa-Nish-Travel.mp3",
    progress: 0,
    category: "Travel",
    learningPoints: ["Travel vocabulary in Spanish", "Asking for directions", "Making reservations"],
    vocabularyWords: [
      "El viaje",
      "El hotel",
      "El aeropuerto",
      "El pasaporte",
      "La maleta",
      "El boleto",
      "La reservación",
      "El turista",
      "La playa",
      "La montaña",
    ],
  },
  {
    id: "19",
    slug: "espanoletry-adjectives",
    title: "Españoletry (Adjectives)",
    description: "Master Spanish adjectives through music and rhythm.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Espanoletry-Adjectives.mp3",
    progress: 0,
    category: "Grammar",
    learningPoints: [
      "Common Spanish adjectives",
      "Adjective agreement (gender and number)",
      "Adjective placement in sentences",
    ],
    vocabularyWords: [
      "Grande",
      "Pequeño/a",
      "Bueno/a",
      "Malo/a",
      "Feliz",
      "Triste",
      "Rápido/a",
      "Lento/a",
      "Nuevo/a",
      "Viejo/a",
      "Interesante",
      "Aburrido/a",
    ],
  },
  {
    id: "20",
    slug: "bored-in-the-house",
    title: "Bored in the House (House)",
    description: "Learn vocabulary for rooms and items in a house.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Bored-in-the-House-House.mp3",
    progress: 0,
    category: "Home",
    learningPoints: ["Rooms in a house", "Furniture and household items", "Activities at home"],
    vocabularyWords: [
      "La casa",
      "La sala",
      "La cocina",
      "El dormitorio",
      "El baño",
      "El comedor",
      "La mesa",
      "La silla",
      "La cama",
      "El sofá",
      "La televisión",
      "La ventana",
      "La puerta",
    ],
  },
  {
    id: "21",
    slug: "kankakee-places",
    title: "Kankakee (Places)",
    description: "Learn vocabulary for places in a city or town.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Kankakee-Places.mp3",
    progress: 0,
    category: "Places",
    learningPoints: ["Places in a city or town", "Giving and asking for directions", "Describing locations"],
    vocabularyWords: [
      "La ciudad",
      "El pueblo",
      "La calle",
      "La tienda",
      "El restaurante",
      "El parque",
      "La escuela",
      "La biblioteca",
      "El museo",
      "El cine",
      "El supermercado",
      "La estación",
    ],
  },
  {
    id: "22",
    slug: "and-teach-clothing-jobs",
    title: "And Teach (Clothing & Jobs)",
    description: "Learn vocabulary for clothing items and professions.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/And-Teach-Clothing-Jobs.mp3",
    progress: 0,
    category: "Vocabulary",
    learningPoints: ["Clothing vocabulary", "Profession and job vocabulary", "Describing what people wear and do"],
    vocabularyWords: [
      "La ropa",
      "La camisa",
      "Los pantalones",
      "El vestido",
      "Los zapatos",
      "El trabajo",
      "El/La profesor/a",
      "El/La doctor/a",
      "El/La abogado/a",
      "El/La ingeniero/a",
      "El/La artista",
    ],
  },
  {
    id: "23",
    slug: "book-dun-classroom",
    title: "Book Dun (Classroom)",
    description: "Learn vocabulary for classroom objects and activities.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Book-Dun-Classroom.mp3",
    progress: 0,
    category: "Education",
    learningPoints: ["Classroom vocabulary", "School supplies", "Classroom activities and commands"],
    vocabularyWords: [
      "La clase",
      "El/La estudiante",
      "El/La maestro/a",
      "El libro",
      "El cuaderno",
      "El lápiz",
      "La pluma",
      "La mochila",
      "La pizarra",
      "La tarea",
      "El examen",
    ],
  },

  // Keep the rest of the lessons...
  {
    id: "3",
    slug: "colors-colores",
    title: "Colors - Colores",
    description: "Learn essential Spanish colors with visual associations and proper pronunciation through music.",
    videoUrl: "https://www.youtube.com/watch?v=l0W4vdQKYbI",
    worksheetUrl: "/worksheets/colors-colores.pdf",
    audioUrl: "/audio/lessons/colors-lesson.mp3",
    progress: 0,
    category: "Vocabulary",
    difficulty: "beginner",
    duration: "10 min",
    isFeatured: true,
    learningPoints: [
      "Master basic color vocabulary",
      "Understand color adjective agreement",
      "Describe objects using colors",
      "Practice pronunciation with visual cues",
    ],
    vocabularyWords: [
      "Rojo - Red",
      "Azul - Blue",
      "Verde - Green",
      "Amarillo - Yellow",
      "Negro - Black",
      "Blanco - White",
      "Morado - Purple",
      "Rosa - Pink",
      "Gris - Gray",
      "Marrón - Brown",
      "Anaranjado - Orange",
      "Rosado - Pink",
    ],
    thumbnail: "/spanish-colors-rainbow-lesson.png",
  },
  {
    id: "4",
    slug: "family-familia",
    title: "Family - La Familia",
    description: "Learn Spanish vocabulary for family members and relationships through engaging music.",
    videoUrl: null,
    worksheetUrl: "/worksheets/family-familia.pdf",
    audioUrl: "/audio/lessons/family-lesson.mp3",
    progress: 0,
    category: "Family",
    difficulty: "beginner",
    duration: "15 min",
    learningPoints: [
      "Name family members in Spanish",
      "Describe family relationships",
      "Use possessive pronouns with family",
      "Talk about your family structure",
    ],
    vocabularyWords: [
      "La familia - The family",
      "El padre - The father",
      "La madre - The mother",
      "El hermano - The brother",
      "La hermana - The sister",
      "El abuelo - The grandfather",
      "La abuela - The grandmother",
      "El tío - The uncle",
      "La tía - The aunt",
      "El primo - The cousin (male)",
      "La prima - The cousin (female)",
      "El hijo - The son",
      "La hija - The daughter",
      "Los padres - The parents",
      "Los hermanos - The siblings",
    ],
    thumbnail: "/spanish-family-members.png",
  },
  {
    id: "5",
    slug: "body-parts-cuerpo",
    title: "Body Parts - El Cuerpo",
    description: "Learn Spanish vocabulary for body parts through hip hop music and interactive exercises.",
    videoUrl: "https://www.youtube.com/watch?v=0KbRb6Qt34s",
    worksheetUrl: "/worksheets/body-parts-cuerpo.pdf",
    audioUrl: "/audio/lessons/body-parts-lesson.mp3",
    progress: 0,
    category: "Health",
    difficulty: "beginner",
    duration: "14 min",
    learningPoints: [
      "Name body parts in Spanish",
      "Use body parts in sentences",
      "Understand health-related vocabulary",
      "Practice pronunciation with gestures",
    ],
    vocabularyWords: [
      "La cabeza - The head",
      "Los ojos - The eyes",
      "La nariz - The nose",
      "La boca - The mouth",
      "Las orejas - The ears",
      "El cuello - The neck",
      "Los brazos - The arms",
      "Las manos - The hands",
      "Los dedos - The fingers",
      "El pecho - The chest",
      "La espalda - The back",
      "Las piernas - The legs",
      "Los pies - The feet",
      "El estómago - The stomach",
    ],
    thumbnail: "/spanish-body-parts.png",
  },
  {
    id: "6",
    slug: "weather-tiempo",
    title: "Weather - El Tiempo",
    description: "Learn to describe weather conditions and seasons in Spanish through engaging music.",
    videoUrl: null,
    worksheetUrl: "/worksheets/weather-tiempo.pdf",
    audioUrl: "/audio/lessons/weather-lesson.mp3",
    progress: 0,
    category: "Nature",
    difficulty: "beginner",
    duration: "11 min",
    learningPoints: [
      "Describe weather conditions",
      "Name the four seasons",
      "Use weather expressions",
      "Have weather conversations",
    ],
    vocabularyWords: [
      "El tiempo - The weather",
      "Hace calor - It's hot",
      "Hace frío - It's cold",
      "Llueve - It's raining",
      "Nieva - It's snowing",
      "Hace sol - It's sunny",
      "Hace viento - It's windy",
      "Está nublado - It's cloudy",
      "La primavera - Spring",
      "El verano - Summer",
      "El otoño - Fall",
      "El invierno - Winter",
    ],
    thumbnail: "/spanish-weather-seasons.png",
  },
  {
    id: "7",
    slug: "places-lugares",
    title: "Places - Los Lugares",
    description: "Learn vocabulary for places in the city and neighborhood through hip-hop music.",
    videoUrl: null,
    worksheetUrl: "/worksheets/places-lugares.pdf",
    audioUrl: "/audio/lessons/places-lesson.mp3",
    progress: 0,
    category: "Places",
    difficulty: "intermediate",
    duration: "16 min",
    learningPoints: [
      "Name places in the city",
      "Give and understand directions",
      "Describe locations",
      "Use prepositions of place",
    ],
    vocabularyWords: [
      "La ciudad - The city",
      "La casa - The house",
      "La escuela - The school",
      "El parque - The park",
      "La tienda - The store",
      "El banco - The bank",
      "El hospital - The hospital",
      "La iglesia - The church",
      "El restaurante - The restaurant",
      "La biblioteca - The library",
      "El cine - The movie theater",
      "El supermercado - The supermarket",
    ],
    thumbnail: "/spanish-city-neighborhood-lesson.png",
  },
  {
    id: "8",
    slug: "food-comida",
    title: "Food - La Comida",
    description: "Learn Spanish vocabulary for food, meals, and dining through engaging music.",
    videoUrl: null,
    worksheetUrl: "/worksheets/food-comida.pdf",
    audioUrl: "/audio/lessons/food-lesson.mp3",
    progress: 0,
    category: "Food",
    difficulty: "intermediate",
    duration: "18 min",
    learningPoints: [
      "Name foods and meals",
      "Order food in Spanish",
      "Describe food preferences",
      "Use food-related expressions",
    ],
    vocabularyWords: [
      "La comida - The food",
      "El desayuno - Breakfast",
      "El almuerzo - Lunch",
      "La cena - Dinner",
      "El pan - Bread",
      "La leche - Milk",
      "Los huevos - Eggs",
      "La carne - Meat",
      "El pollo - Chicken",
      "El pescado - Fish",
      "Las frutas - Fruits",
      "Las verduras - Vegetables",
      "El agua - Water",
      "El jugo - Juice",
    ],
    thumbnail: "/spanish-food-lesson.png",
  },
  {
    id: "9",
    slug: "animales",
    title: "Animals (Bienvenido a la Selva)",
    description: "Learn Spanish vocabulary for animals from pets to wildlife.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: "/audio/Bienvenido-a-la-Selva-Animals.mp3",
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Name common animals in Spanish",
      "Describe animals and their characteristics",
      "Use animal vocabulary in conversations",
    ],
    vocabularyWords: [
      "Búfalo",
      "Caballo",
      "Pájaro",
      "Conejo",
      "Pez",
      "Los osos",
      "Los toros",
      "Cerdo",
      "El león",
      "Tortuga",
      "Hamster",
      "El elefante",
      "El canguro",
      "Una panda",
      "Ardilla",
      "Abejas",
      "Trucha",
      "El rinoceronte",
      "Vaca",
      "Gato",
      "Un perro",
    ],
  },
  {
    id: "10",
    slug: "salas-y-muebles",
    title: "Rooms & Furniture (Salas y Muebles)",
    description: "Learn Spanish vocabulary for rooms in a house and furniture.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: "/audio/Chill-en-Mi-Casa-House.mp3",
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Name rooms in a house in Spanish",
      "Identify common furniture items",
      "Describe your home using correct vocabulary",
    ],
    vocabularyWords: [
      "Mi casa",
      "La entrada",
      "La puerta",
      "La alfombra",
      "La cocina",
      "El horno",
      "La mesa",
      "La silla",
      "El refrigerador",
      "La sala",
      "Estantería para libros",
      "El escritorio",
      "El sofá",
      "La lámpara",
      "La ventana",
      "Cuarto del baño",
      "El lavabo",
      "El inodoro",
      "La bañera",
      "El cuarto",
      "El armario",
      "La televisión",
      "Cama",
      "El apartamento",
    ],
  },
  {
    id: "11",
    slug: "comida",
    title: "Time to Eat (Ya Comí)",
    description: "Learn Spanish vocabulary for food, meals, and dining.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: null,
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Name foods and meals in Spanish",
      "Learn vocabulary for fruits, vegetables, and other food groups",
      "Describe your food preferences in Spanish",
    ],
    vocabularyWords: [
      "Desayuno",
      "Frutas",
      "Fresas",
      "Manzanas",
      "Frambuesas",
      "Verduras",
      "Ensalada",
      "Espinaca",
      "Zanahorias",
      "Pepinos",
      "Naranjas",
      "Agua",
      "Tomate",
      "Brécol",
      "Huevos",
      "Tocino",
      "Leche",
      "Queso",
      "Almuerzo",
      "Un sándwich",
      "Pan",
      "Mostaza",
      "Mayonesa",
      "Pavo",
      "Lechuga",
      "Bananos",
      "Uvas",
      "Col rizada",
      "Jugo",
      "Cena",
      "Bistec",
      "Pollo",
      "Pescado",
      "Helado",
      "Arroz",
      "Gambas",
      "Maíz",
      "Sal",
      "Pimiento",
    ],
  },

  // Keep some of the original lessons
  {
    id: "12",
    slug: "juli-slide",
    title: "Juli Slide",
    description: "Learn common Spanish phrases and expressions through music.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: null,
    progress: 0,
    category: "Vocabulary",
    learningPoints: ["Common Spanish expressions", "Conversational phrases", "Cultural context for expressions"],
  },
  {
    id: "13",
    slug: "que-pasa",
    title: "¿Qué Pasa?",
    description: "Learn question words and conversation starters in Spanish.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: null,
    progress: 0,
    category: "Vocabulary",
    learningPoints: ["Spanish question words", "Forming basic questions", "Common conversation starters"],
  },

  // New lessons from the latest content
  {
    id: "32",
    slug: "que-tiempo-hace-weather",
    title: "¿Qué Tiempo Hace? (Weather)",
    description: "Learn Spanish vocabulary for weather conditions and seasons.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Weather-Que-Tiempo-Hace-Worksheet.pdf",
    audioUrl: "/audio/Que-Tiempo-Hace-Weather.mp3",
    progress: 0,
    category: "Vocabulary",
    learningPoints: ["Weather expressions in Spanish", "Seasonal vocabulary", "Describing climate conditions"],
    vocabularyWords: [
      "Qué tiempo hace",
      "Hace calor",
      "Llueve",
      "Hace frío",
      "Hace viento",
      "Hace mal tiempo",
      "Hace buen tiempo",
      "Verano",
      "Invierno",
      "El otoño",
      "Primavera",
    ],
  },
  {
    id: "33",
    slug: "conjugation-thang",
    title: "Conjugation Thang (Present & Preterite)",
    description: "Master Spanish verb conjugations in present and preterite tenses.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Conjugation-Thang-Worksheet.pdf",
    audioUrl: "/audio/Conjugation-Thang.mp3",
    progress: 0,
    category: "Grammar",
    learningPoints: [
      "Present tense conjugation patterns",
      "Preterite tense conjugation patterns",
      "Regular verb endings for -ar, -er, and -ir verbs",
    ],
    vocabularyWords: [
      "-o, -as, -a, -amos, -an",
      "-o, -es, -e, -emos, -en",
      "-o, -es, -e, -imos, -en",
      "-é, -aste, -ó, -amos, -aron",
      "-í, -iste, -ió, -imos, -ieron",
      "Hablar",
      "Comer",
      "Vivir",
      "Pretérito",
    ],
  },
  {
    id: "34",
    slug: "teach-that-prepositions-extended",
    title: "Teach That (Prepositions Extended)",
    description: "Comprehensive guide to Spanish prepositions of location and position.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Prepositions-Teach-That-Extended-Worksheet.pdf",
    audioUrl: "/audio/Teach-That-Prepositions-Extended.mp3",
    progress: 0,
    category: "Grammar",
    learningPoints: [
      "Prepositions of location in Spanish",
      "Using prepositions to describe position",
      "Combining prepositions with other words",
    ],
    vocabularyWords: [
      "Debajo de",
      "Encima de",
      "Cerca de",
      "Lejos de",
      "En frente de",
      "Detrás de",
      "Al lado de",
      "Está sobre",
      "Está",
      "De",
    ],
  },
  {
    id: "35",
    slug: "talkin-family-extended-2",
    title: "Talkin' Family (Extended)",
    description: "Comprehensive vocabulary for family members and relationships in Spanish.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Family-Talkin-Family-Extended-Worksheet.pdf",
    audioUrl: "/audio/Talkin-Family-Extended-2.mp3",
    progress: 0,
    category: "Vocabulary",
    learningPoints: [
      "Immediate and extended family vocabulary",
      "Describing family relationships",
      "Talking about your family in Spanish",
    ],
    vocabularyWords: [
      "Familia",
      "Padres",
      "Madre",
      "Padre",
      "Tío",
      "Tía",
      "Hermana",
      "Hermano",
      "Hijas",
      "Hijos",
      "Abuelo",
      "Abuela",
      "Sobrina",
      "Sobrino",
      "Primo",
    ],
  },
  {
    id: "36",
    slug: "book-dun-classroom-extended",
    title: "Book Dun (Classroom Extended)",
    description: "Comprehensive vocabulary for classroom objects, school subjects, and academic activities.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Classroom-Books-Dun-Extended-Worksheet.pdf",
    audioUrl: "/audio/Book-Dun-Classroom-Extended.mp3",
    progress: 0,
    category: "Education",
    learningPoints: [
      "Classroom vocabulary",
      "School supplies and equipment",
      "School subjects and academic activities",
    ],
    vocabularyWords: [
      "La clase",
      "Maestro",
      "Estudiantes",
      "Mochila",
      "Cuaderno",
      "Papel",
      "Escritorio",
      "La computadora",
      "El cartel",
      "La mesa",
      "La tarea",
      "La silla",
      "La puerta",
      "La papelera",
      "La ventana",
      "La bandera",
      "El ratón",
      "La pantalla",
      "El diccionario",
      "Matemáticas",
      "El arte",
      "Ciencias sociales",
      "Ciencias naturales",
      "Educación física",
    ],
  },
  {
    id: "37",
    slug: "espanoletry-adjectives-complete",
    title: "Españoletry (Adjectives Complete)",
    description: "Master Spanish adjectives for describing people, places, and things.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Adjectives-Espanoletry-Complete-Worksheet.pdf",
    audioUrl: "/audio/Espanoletry-Adjectives-Complete.mp3",
    progress: 0,
    category: "Grammar",
    learningPoints: [
      "Personality and physical description adjectives",
      "Gender and number agreement with adjectives",
      "Adjective placement in sentences",
    ],
    vocabularyWords: [
      "El chico",
      "Artístico",
      "El amigo",
      "Atrevido",
      "La chica",
      "Tímido",
      "Serio",
      "Trabajador",
      "Artero",
      "Sociable",
      "Talentoso",
      "Estudioso",
      "Reservado",
      "Ordenados",
      "Gracioso",
      "Perezoso",
      "Paciente",
      "Impaciente",
      "Desordenado",
      "Simpático",
      "Inteligente",
    ],
  },
  {
    id: "38",
    slug: "i-look-good-extended",
    title: "I Look Good (Extended)",
    description: "Comprehensive vocabulary for physical descriptions and appearance in Spanish.",
    videoUrl: null,
    worksheetUrl: "/worksheets/I-Look-Good-Extended-Worksheet.pdf",
    audioUrl: "/audio/I-Look-Good-Extended.mp3",
    progress: 0,
    category: "Descriptions",
    learningPoints: [
      "Physical appearance vocabulary",
      "Body features and characteristics",
      "Describing people's appearance in Spanish",
    ],
    vocabularyWords: [
      "Bella",
      "Estúpido",
      "Viejo",
      "Joven",
      "Débil",
      "Inteligente",
      "Bajo",
      "Alto",
      "Perezoso",
      "Pelo largo",
      "Calvo",
      "Ojos marrones",
      "La boca ancha",
      "Gordo",
      "Piel morena",
      "Delgada",
      "Un lunar",
      "Hoyuelos",
      "Pecas",
      "Labios carnosos",
      "Guapo",
      "Creativo",
      "Seria",
      "Emocionado",
      "Fuerte",
    ],
  },
  {
    id: "39",
    slug: "the-abcds",
    title: "The ABCDs (Spanish Alphabet)",
    description: "Learn the Spanish alphabet with proper pronunciation.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Alphabet-The-ABCDs-Worksheet.pdf",
    audioUrl: "/audio/The-ABCDs-Alphabet.mp3",
    progress: 0,
    category: "Fundamentals",
    learningPoints: ["Spanish alphabet pronunciation", "Letter recognition", "Spelling in Spanish"],
    vocabularyWords: [
      "El alfabeto",
      "A (ah)",
      "B (bay)",
      "C (say)",
      "D (day)",
      "E (ay)",
      "F (ef-fay)",
      "G (hey)",
      "H (a-chay)",
      "I (eee)",
      "J (hoe-tah)",
      "K (ka)",
      "L (el-ay)",
      "M (em-ay)",
      "N (en-ay)",
      "Ñ (en-yay)",
      "O (oh)",
      "P (pay)",
      "Q (coo)",
      "R (air-ray)",
      "S (es-say)",
      "T (teh)",
      "U (oo)",
      "V (bay)",
      "W (do-bleh bay)",
      "X (eh-keys)",
      "Y (ih-gree-ay-gah)",
      "Z (say-tah)",
    ],
  },
  {
    id: "40",
    slug: "juli-slide-extended",
    title: "Juli Slide (Alphabet Extended)",
    description: "Learn the Spanish alphabet and vocabulary with each letter.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Alphabet-Juli-Slide-Extended-Worksheet.pdf",
    audioUrl: "/audio/Juli-Slide-Extended.mp3",
    progress: 0,
    category: "Fundamentals",
    learningPoints: [
      "Spanish alphabet pronunciation",
      "Vocabulary associated with each letter",
      "Cultural and social justice vocabulary in Spanish",
    ],
    vocabularyWords: [
      "Abolicionista",
      "Ambiente",
      "Activista",
      "Bandera",
      "Boicot",
      "Cooperar",
      "Clima",
      "Discapacidad",
      "Español",
      "Feminista",
      "Humanidad",
      "Imaginación",
      "Justicia",
      "Liberación",
      "Migrante",
      "Naturalista",
      "Optimista",
      "Posible",
      "Revolución",
      "Sexualidad",
      "Transgenero",
      "Unión",
      "Visible",
      "Xenofobia",
      "Zapatista",
    ],
  },
]

// Function to get featured lessons for homepage
export function getFeaturedLessons(): Lesson[] {
  return lessons.filter((lesson) => lesson.isFeatured).slice(0, 6)
}

export function getLessonsByCategory(category: string): Lesson[] {
  return lessons.filter((lesson) => lesson.category === category)
}

export function getLessonBySlug(slug: string): Lesson | undefined {
  return lessons.find((lesson) => lesson.slug === slug)
}
