import type { Lesson } from "@/lib/types"

export const lessons: Lesson[] = [
  // Colors lesson - matching the URL
  {
    id: "7",
    slug: "colors-colores",
    title: "Colors (Colores)",
    description: "Master Spanish color vocabulary with catchy music.",
    videoUrl: "https://www.youtube.com/watch?v=l0W4vdQKYbI",
    worksheetUrl: "#",
    audioUrl: null,
    progress: 30,
    category: "Un Día en La Vida",
    learningPoints: ["Basic color names in Spanish", "Color adjective agreement", "Describing objects using colors"],
    vocabularyWords: [
      "Verde",
      "Negro",
      "Azul",
      "Blanco",
      "Morado",
      "Anaranjado",
      "Rojo",
      "Marrón",
      "Amarillo",
      "Gris",
      "Rosado",
    ],
    thumbnail: "/spanish-colors-rainbow-lesson.png",
  },

  // Original lesson
  {
    id: "1",
    slug: "cuerpo",
    title: "Cuerpo (Body Parts)",
    description: "Learn Spanish vocabulary for body parts through hip hop music.",
    videoUrl: "https://www.youtube.com/watch?v=0KbRb6Qt34s",
    worksheetUrl: "#",
    audioUrl: null,
    progress: 75,
    category: "Vocabulary",
    learningPoints: [
      "Names of body parts in Spanish",
      "Possessive pronouns with body parts",
      "Using body parts in simple sentences",
    ],
    thumbnail: "/spanish-body-parts.png",
  },

  // Add the alfabeto lesson
  {
    id: "41",
    slug: "alfabeto",
    title: "El Alfabeto (Spanish Alphabet)",
    description: "Master the Spanish alphabet with proper pronunciation and letter recognition.",
    videoUrl: "https://www.youtube.com/watch?v=uOQMDaWSn6c",
    worksheetUrl: "/worksheets/Alphabet-The-ABCDs-Worksheet.pdf",
    audioUrl: "/audio/Juli-Slide-Alphabet.mp3",
    progress: 0,
    category: "Fundamentals",
    learningPoints: [
      "Spanish alphabet pronunciation",
      "Letter recognition and spelling",
      "Difference between Spanish and English alphabet",
      "Special letters: Ñ, RR, LL",
    ],
    vocabularyWords: [
      "El alfabeto",
      "Las letras",
      "A (ah)",
      "B (bay)",
      "C (say)",
      "D (day)",
      "E (ay)",
      "F (ef-fay)",
      "G (hey)",
      "H (a-chay)",
      "I (eee)",
      "J (hoe-tah)",
      "K (ka)",
      "L (el-ay)",
      "M (em-ay)",
      "N (en-ay)",
      "Ñ (en-yay)",
      "O (oh)",
      "P (pay)",
      "Q (coo)",
      "R (air-ray)",
      "S (es-say)",
      "T (teh)",
      "U (oo)",
      "V (bay)",
      "W (do-bleh bay)",
      "X (eh-keys)",
      "Y (ih-gree-ay-gah)",
      "Z (say-tah)",
    ],
    thumbnail: "/spanish-alphabet-lesson.png",
  },

  // Un Día en La Vida lessons
  {
    id: "2",
    slug: "numeros",
    title: "Numbers (0 to 101)",
    description: "Master counting in Spanish from zero to one hundred and one.",
    videoUrl: "https://www.youtube.com/watch?v=iVkolTR98ew",
    worksheetUrl: "/worksheets/Numbers-0-to-101-Worksheet.pdf",
    audioUrl: null,
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Count from 0 to 101 in Spanish",
      "Understand number patterns and formation",
      "Use numbers in practical situations",
    ],
    vocabularyWords: [
      "Cero",
      "Uno",
      "Dos",
      "Tres",
      "Cuatro",
      "Cinco",
      "Seis",
      "Siete",
      "Ocho",
      "Nueve",
      "Diez",
      "Once",
      "Doce",
      "Trece",
      "Catorce",
      "Quince",
      "Dieciseis",
      "Diecinueve",
      "Veinte",
      "Treinta",
      "Cuarenta",
      "Cincuenta",
      "Sesenta",
      "Setenta",
      "Ochenta",
      "Noventa",
      "Cien",
    ],
    thumbnail: "/spanish-numbers-lesson.png",
  },

  // Additional lessons with audio files
  {
    id: "14",
    slug: "juli-slide-alphabet",
    title: "Juli Slide (Alphabet)",
    description: "Learn the Spanish alphabet through a catchy hip hop song with rhythm and flow.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Juli-Slide-Alphabet.mp3",
    progress: 0,
    category: "Fundamentals",
    learningPoints: ["Spanish alphabet pronunciation", "Letter recognition", "Spelling in Spanish"],
    vocabularyWords: [
      "El alfabeto",
      "Las letras",
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H",
      "I",
      "J",
      "K",
      "L",
      "M",
      "N",
      "Ñ",
      "O",
      "P",
      "Q",
      "R",
      "S",
      "T",
      "U",
      "V",
      "W",
      "X",
      "Y",
      "Z",
    ],
  },
  {
    id: "15",
    slug: "puff-lah",
    title: "Puff Lah",
    description: "A fun hip-hop song to help you learn essential Spanish vocabulary with rhythm.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Puff-Lah.mp3",
    progress: 0,
    category: "Vocabulary",
    learningPoints: ["Essential Spanish vocabulary", "Pronunciation practice", "Rhythm and flow in Spanish"],
    vocabularyWords: ["Hola", "Adiós", "Gracias", "Por favor", "Sí", "No", "Buenos días", "Buenas noches"],
  },
  {
    id: "16",
    slug: "i-look-good",
    title: "I Look Good (Me Parece Guapo)",
    description: "Learn appearance and description vocabulary in Spanish through music.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/I-Look-Good-Me-Parece-Guapo.mp3",
    progress: 0,
    category: "Descriptions",
    learningPoints: ["Appearance vocabulary", "Self-description in Spanish", "Using 'parecer' and related verbs"],
    vocabularyWords: [
      "Guapo/a",
      "Bonito/a",
      "Alto/a",
      "Bajo/a",
      "Delgado/a",
      "Gordo/a",
      "Fuerte",
      "Me parece",
      "Se ve",
    ],
  },
  {
    id: "17",
    slug: "the-docs-health",
    title: "The Docs (Health)",
    description: "Learn health and medical vocabulary in Spanish through engaging music.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/The-Docs-Health.mp3",
    progress: 0,
    category: "Health",
    learningPoints: ["Medical vocabulary in Spanish", "Describing symptoms", "Doctor's visit conversations"],
    vocabularyWords: [
      "El doctor/La doctora",
      "El hospital",
      "La enfermedad",
      "El dolor",
      "La medicina",
      "La receta",
      "La farmacia",
      "Enfermo/a",
      "Sano/a",
    ],
  },
  {
    id: "18",
    slug: "spa-nish-travel",
    title: "Spa Nish (Travel)",
    description: "Essential Spanish vocabulary for travelers through catchy hip-hop beats.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Spa-Nish-Travel.mp3",
    progress: 0,
    category: "Travel",
    learningPoints: ["Travel vocabulary in Spanish", "Asking for directions", "Making reservations"],
    vocabularyWords: [
      "El viaje",
      "El hotel",
      "El aeropuerto",
      "El pasaporte",
      "La maleta",
      "El boleto",
      "La reservación",
      "El turista",
      "La playa",
      "La montaña",
    ],
  },
  {
    id: "19",
    slug: "espanoletry-adjectives",
    title: "Españoletry (Adjectives)",
    description: "Master Spanish adjectives through music and rhythm.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Espanoletry-Adjectives.mp3",
    progress: 0,
    category: "Grammar",
    learningPoints: [
      "Common Spanish adjectives",
      "Adjective agreement (gender and number)",
      "Adjective placement in sentences",
    ],
    vocabularyWords: [
      "Grande",
      "Pequeño/a",
      "Bueno/a",
      "Malo/a",
      "Feliz",
      "Triste",
      "Rápido/a",
      "Lento/a",
      "Nuevo/a",
      "Viejo/a",
      "Interesante",
      "Aburrido/a",
    ],
  },
  {
    id: "20",
    slug: "bored-in-the-house",
    title: "Bored in the House (House)",
    description: "Learn vocabulary for rooms and items in a house.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Bored-in-the-House-House.mp3",
    progress: 0,
    category: "Home",
    learningPoints: ["Rooms in a house", "Furniture and household items", "Activities at home"],
    vocabularyWords: [
      "La casa",
      "La sala",
      "La cocina",
      "El dormitorio",
      "El baño",
      "El comedor",
      "La mesa",
      "La silla",
      "La cama",
      "El sofá",
      "La televisión",
      "La ventana",
      "La puerta",
    ],
  },
  {
    id: "21",
    slug: "kankakee-places",
    title: "Kankakee (Places)",
    description: "Learn vocabulary for places in a city or town.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Kankakee-Places.mp3",
    progress: 0,
    category: "Places",
    learningPoints: ["Places in a city or town", "Giving and asking for directions", "Describing locations"],
    vocabularyWords: [
      "La ciudad",
      "El pueblo",
      "La calle",
      "La tienda",
      "El restaurante",
      "El parque",
      "La escuela",
      "La biblioteca",
      "El museo",
      "El cine",
      "El supermercado",
      "La estación",
    ],
  },
  {
    id: "22",
    slug: "and-teach-clothing-jobs",
    title: "And Teach (Clothing & Jobs)",
    description: "Learn vocabulary for clothing items and professions.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/And-Teach-Clothing-Jobs.mp3",
    progress: 0,
    category: "Vocabulary",
    learningPoints: ["Clothing vocabulary", "Profession and job vocabulary", "Describing what people wear and do"],
    vocabularyWords: [
      "La ropa",
      "La camisa",
      "Los pantalones",
      "El vestido",
      "Los zapatos",
      "El trabajo",
      "El/La profesor/a",
      "El/La doctor/a",
      "El/La abogado/a",
      "El/La ingeniero/a",
      "El/La artista",
    ],
  },
  {
    id: "23",
    slug: "book-dun-classroom",
    title: "Book Dun (Classroom)",
    description: "Learn vocabulary for classroom objects and activities.",
    videoUrl: null,
    worksheetUrl: "#",
    audioUrl: "/audio/Book-Dun-Classroom.mp3",
    progress: 0,
    category: "Education",
    learningPoints: ["Classroom vocabulary", "School supplies", "Classroom activities and commands"],
    vocabularyWords: [
      "La clase",
      "El/La estudiante",
      "El/La maestro/a",
      "El libro",
      "El cuaderno",
      "El lápiz",
      "La pluma",
      "La mochila",
      "La pizarra",
      "La tarea",
      "El examen",
    ],
  },

  // Keep the rest of the lessons...
  {
    id: "3",
    slug: "tiempo",
    title: "Time (Time Ain't Hard to Tell)",
    description: "Learn how to tell time in Spanish through music.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "/worksheets/Time-Ain't-Hard-to-Tell-Worksheet.pdf",
    audioUrl: "/audio/Time-Aint-Hard-to-Tell.mp3",
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Tell time in Spanish",
      "Understand time-related expressions",
      "Distinguish between morning, afternoon, and evening",
    ],
    vocabularyWords: [
      "Es la una",
      "Son las",
      "Y",
      "De la",
      "Mañana",
      "Tarde",
      "Noche",
      "Doce",
      "Y treinta",
      "Media",
      "Cuarto",
      "Ocho y cuarto de la noche",
    ],
    thumbnail: "/spanish-telling-time.png",
  },
  {
    id: "4",
    slug: "preposiciones",
    title: "Prepositions (We in There Tho)",
    description: "Master Spanish prepositions to describe location and position.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: null,
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Use prepositions to describe location",
      "Understand position and direction in Spanish",
      "Apply prepositions in everyday conversations",
    ],
    vocabularyWords: [
      "Detrás",
      "Debajo",
      "Adentro",
      "Está",
      "Están",
      "De",
      "Cerca",
      "Lejos",
      "Encima",
      "Afuera",
      "Al lado",
      "La derecha",
      "La izquierda",
      "Sobre",
      "Al frente",
    ],
  },
  {
    id: "5",
    slug: "lugares",
    title: "Places (The Corner)",
    description: "Learn Spanish vocabulary for places in the city and neighborhood.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: null,
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Name common places in a city in Spanish",
      "Give and understand directions",
      "Describe locations in your neighborhood",
    ],
    vocabularyWords: [
      "El metro",
      "La parada de buses",
      "Los edificios",
      "Centro comercial",
      "El gimnasio",
      "La iglesia",
      "El banco",
      "Una casa",
      "Apartamento",
      "Un estudio",
      "El restaurante",
      "El cine",
      "El correo",
      "La librería",
      "El café",
      "La biblioteca",
      "Cuadras",
      "La esquina",
      "La oficina",
    ],
  },
  {
    id: "6",
    slug: "clima",
    title: "Weather (¿Qué Tiempo Hace?)",
    description: "Learn to talk about weather and seasons in Spanish.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: "/audio/Que-Que-Que-Weather.mp3",
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Describe weather conditions in Spanish",
      "Name the four seasons",
      "Have conversations about the weather",
    ],
    vocabularyWords: [
      "Hace calor",
      "Llueve",
      "Hace frío",
      "Hace viento",
      "Hace mal tiempo",
      "Hace sol",
      "Verano",
      "Otoño",
      "Nieva",
      "Invierno",
      "La primavera",
      "Hace fresco",
      "El tiempo",
    ],
  },
  {
    id: "8",
    slug: "familia",
    title: "Family (Meet the Fam Bam)",
    description: "Learn Spanish vocabulary for family members and relationships.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: null,
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Name family members in Spanish",
      "Describe family relationships",
      "Talk about your own family in Spanish",
    ],
    vocabularyWords: [
      "La familia",
      "Hermanas",
      "Los hermanos",
      "Mi madre",
      "Mi padre",
      "Tíos",
      "Tías",
      "Hija",
      "Sobrina",
      "Hijo",
      "Sobrino",
      "Tío",
      "Primo",
      "Prima",
      "Los abuelos",
      "Las abuelas",
    ],
  },
  {
    id: "9",
    slug: "animales",
    title: "Animals (Bienvenido a la Selva)",
    description: "Learn Spanish vocabulary for animals from pets to wildlife.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: "/audio/Bienvenido-a-la-Selva-Animals.mp3",
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Name common animals in Spanish",
      "Describe animals and their characteristics",
      "Use animal vocabulary in conversations",
    ],
    vocabularyWords: [
      "Búfalo",
      "Caballo",
      "Pájaro",
      "Conejo",
      "Pez",
      "Los osos",
      "Los toros",
      "Cerdo",
      "El león",
      "Tortuga",
      "Hamster",
      "El elefante",
      "El canguro",
      "Una panda",
      "Ardilla",
      "Abejas",
      "Trucha",
      "El rinoceronte",
      "Vaca",
      "Gato",
      "Un perro",
    ],
  },
  {
    id: "10",
    slug: "salas-y-muebles",
    title: "Rooms & Furniture (Salas y Muebles)",
    description: "Learn Spanish vocabulary for rooms in a house and furniture.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: "/audio/Chill-en-Mi-Casa-House.mp3",
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Name rooms in a house in Spanish",
      "Identify common furniture items",
      "Describe your home using correct vocabulary",
    ],
    vocabularyWords: [
      "Mi casa",
      "La entrada",
      "La puerta",
      "La alfombra",
      "La cocina",
      "El horno",
      "La mesa",
      "La silla",
      "El refrigerador",
      "La sala",
      "Estantería para libros",
      "El escritorio",
      "El sofá",
      "La lámpara",
      "La ventana",
      "Cuarto del baño",
      "El lavabo",
      "El inodoro",
      "La bañera",
      "El cuarto",
      "El armario",
      "La televisión",
      "Cama",
      "El apartamento",
    ],
  },
  {
    id: "11",
    slug: "comida",
    title: "Time to Eat (Ya Comí)",
    description: "Learn Spanish vocabulary for food, meals, and dining.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: null,
    progress: 0,
    category: "Un Día en La Vida",
    learningPoints: [
      "Name foods and meals in Spanish",
      "Learn vocabulary for fruits, vegetables, and other food groups",
      "Describe your food preferences in Spanish",
    ],
    vocabularyWords: [
      "Desayuno",
      "Frutas",
      "Fresas",
      "Manzanas",
      "Frambuesas",
      "Verduras",
      "Ensalada",
      "Espinaca",
      "Zanahorias",
      "Pepinos",
      "Naranjas",
      "Agua",
      "Tomate",
      "Brécol",
      "Huevos",
      "Tocino",
      "Leche",
      "Queso",
      "Almuerzo",
      "Un sándwich",
      "Pan",
      "Mostaza",
      "Mayonesa",
      "Pavo",
      "Lechuga",
      "Bananos",
      "Uvas",
      "Col rizada",
      "Jugo",
      "Cena",
      "Bistec",
      "Pollo",
      "Pescado",
      "Helado",
      "Arroz",
      "Gambas",
      "Maíz",
      "Sal",
      "Pimiento",
    ],
  },

  // Keep some of the original lessons
  {
    id: "12",
    slug: "juli-slide",
    title: "Juli Slide",
    description: "Learn common Spanish phrases and expressions through music.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: null,
    progress: 0,
    category: "Vocabulary",
    learningPoints: ["Common Spanish expressions", "Conversational phrases", "Cultural context for expressions"],
  },
  {
    id: "13",
    slug: "que-pasa",
    title: "¿Qué Pasa?",
    description: "Learn question words and conversation starters in Spanish.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    worksheetUrl: "#",
    audioUrl: null,
    progress: 0,
    category: "Vocabulary",
    learningPoints: ["Spanish question words", "Forming basic questions", "Common conversation starters"],
  },

  // New lessons from the latest content
  {
    id: "32",
    slug: "que-tiempo-hace-weather",
    title: "¿Qué Tiempo Hace? (Weather)",
    description: "Learn Spanish vocabulary for weather conditions and seasons.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Weather-Que-Tiempo-Hace-Worksheet.pdf",
    audioUrl: "/audio/Que-Tiempo-Hace-Weather.mp3",
    progress: 0,
    category: "Vocabulary",
    learningPoints: ["Weather expressions in Spanish", "Seasonal vocabulary", "Describing climate conditions"],
    vocabularyWords: [
      "Qué tiempo hace",
      "Hace calor",
      "Llueve",
      "Hace frío",
      "Hace viento",
      "Hace mal tiempo",
      "Hace buen tiempo",
      "Verano",
      "Invierno",
      "El otoño",
      "Primavera",
    ],
  },
  {
    id: "33",
    slug: "conjugation-thang",
    title: "Conjugation Thang (Present & Preterite)",
    description: "Master Spanish verb conjugations in present and preterite tenses.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Conjugation-Thang-Worksheet.pdf",
    audioUrl: "/audio/Conjugation-Thang.mp3",
    progress: 0,
    category: "Grammar",
    learningPoints: [
      "Present tense conjugation patterns",
      "Preterite tense conjugation patterns",
      "Regular verb endings for -ar, -er, and -ir verbs",
    ],
    vocabularyWords: [
      "-o, -as, -a, -amos, -an",
      "-o, -es, -e, -emos, -en",
      "-o, -es, -e, -imos, -en",
      "-é, -aste, -ó, -amos, -aron",
      "-í, -iste, -ió, -imos, -ieron",
      "Hablar",
      "Comer",
      "Vivir",
      "Pretérito",
    ],
  },
  {
    id: "34",
    slug: "teach-that-prepositions-extended",
    title: "Teach That (Prepositions Extended)",
    description: "Comprehensive guide to Spanish prepositions of location and position.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Prepositions-Teach-That-Extended-Worksheet.pdf",
    audioUrl: "/audio/Teach-That-Prepositions-Extended.mp3",
    progress: 0,
    category: "Grammar",
    learningPoints: [
      "Prepositions of location in Spanish",
      "Using prepositions to describe position",
      "Combining prepositions with other words",
    ],
    vocabularyWords: [
      "Debajo de",
      "Encima de",
      "Cerca de",
      "Lejos de",
      "En frente de",
      "Detrás de",
      "Al lado de",
      "Está sobre",
      "Está",
      "De",
    ],
  },
  {
    id: "35",
    slug: "talkin-family-extended-2",
    title: "Talkin' Family (Extended)",
    description: "Comprehensive vocabulary for family members and relationships in Spanish.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Family-Talkin-Family-Extended-Worksheet.pdf",
    audioUrl: "/audio/Talkin-Family-Extended-2.mp3",
    progress: 0,
    category: "Vocabulary",
    learningPoints: [
      "Immediate and extended family vocabulary",
      "Describing family relationships",
      "Talking about your family in Spanish",
    ],
    vocabularyWords: [
      "Familia",
      "Padres",
      "Madre",
      "Padre",
      "Tío",
      "Tía",
      "Hermana",
      "Hermano",
      "Hijas",
      "Hijos",
      "Abuelo",
      "Abuela",
      "Sobrina",
      "Sobrino",
      "Primo",
    ],
  },
  {
    id: "36",
    slug: "book-dun-classroom-extended",
    title: "Book Dun (Classroom Extended)",
    description: "Comprehensive vocabulary for classroom objects, school subjects, and academic activities.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Classroom-Books-Dun-Extended-Worksheet.pdf",
    audioUrl: "/audio/Book-Dun-Classroom-Extended.mp3",
    progress: 0,
    category: "Education",
    learningPoints: [
      "Classroom vocabulary",
      "School supplies and equipment",
      "School subjects and academic activities",
    ],
    vocabularyWords: [
      "La clase",
      "Maestro",
      "Estudiantes",
      "Mochila",
      "Cuaderno",
      "Papel",
      "Escritorio",
      "La computadora",
      "El cartel",
      "La mesa",
      "La tarea",
      "La silla",
      "La puerta",
      "La papelera",
      "La ventana",
      "La bandera",
      "El ratón",
      "La pantalla",
      "El diccionario",
      "Matemáticas",
      "El arte",
      "Ciencias sociales",
      "Ciencias naturales",
      "Educación física",
    ],
  },
  {
    id: "37",
    slug: "espanoletry-adjectives-complete",
    title: "Españoletry (Adjectives Complete)",
    description: "Master Spanish adjectives for describing people, places, and things.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Adjectives-Espanoletry-Complete-Worksheet.pdf",
    audioUrl: "/audio/Espanoletry-Adjectives-Complete.mp3",
    progress: 0,
    category: "Grammar",
    learningPoints: [
      "Personality and physical description adjectives",
      "Gender and number agreement with adjectives",
      "Adjective placement in sentences",
    ],
    vocabularyWords: [
      "El chico",
      "Artístico",
      "El amigo",
      "Atrevido",
      "La chica",
      "Tímido",
      "Serio",
      "Trabajador",
      "Artero",
      "Sociable",
      "Talentoso",
      "Estudioso",
      "Reservado",
      "Ordenados",
      "Gracioso",
      "Perezoso",
      "Paciente",
      "Impaciente",
      "Desordenado",
      "Simpático",
      "Inteligente",
    ],
  },
  {
    id: "38",
    slug: "i-look-good-extended",
    title: "I Look Good (Extended)",
    description: "Comprehensive vocabulary for physical descriptions and appearance in Spanish.",
    videoUrl: null,
    worksheetUrl: "/worksheets/I-Look-Good-Extended-Worksheet.pdf",
    audioUrl: "/audio/I-Look-Good-Extended.mp3",
    progress: 0,
    category: "Descriptions",
    learningPoints: [
      "Physical appearance vocabulary",
      "Body features and characteristics",
      "Describing people's appearance in Spanish",
    ],
    vocabularyWords: [
      "Bella",
      "Estúpido",
      "Viejo",
      "Joven",
      "Débil",
      "Inteligente",
      "Bajo",
      "Alto",
      "Perezoso",
      "Pelo largo",
      "Calvo",
      "Ojos marrones",
      "La boca ancha",
      "Gordo",
      "Piel morena",
      "Delgada",
      "Un lunar",
      "Hoyuelos",
      "Pecas",
      "Labios carnosos",
      "Guapo",
      "Creativo",
      "Seria",
      "Emocionado",
      "Fuerte",
    ],
  },
  {
    id: "39",
    slug: "the-abcds",
    title: "The ABCDs (Spanish Alphabet)",
    description: "Learn the Spanish alphabet with proper pronunciation.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Alphabet-The-ABCDs-Worksheet.pdf",
    audioUrl: "/audio/The-ABCDs-Alphabet.mp3",
    progress: 0,
    category: "Fundamentals",
    learningPoints: ["Spanish alphabet pronunciation", "Letter recognition", "Spelling in Spanish"],
    vocabularyWords: [
      "El alfabeto",
      "A (ah)",
      "B (bay)",
      "C (say)",
      "D (day)",
      "E (ay)",
      "F (ef-fay)",
      "G (hey)",
      "H (a-chay)",
      "I (eee)",
      "J (hoe-tah)",
      "K (ka)",
      "L (el-ay)",
      "M (em-ay)",
      "N (en-ay)",
      "Ñ (en-yay)",
      "O (oh)",
      "P (pay)",
      "Q (coo)",
      "R (air-ray)",
      "S (es-say)",
      "T (teh)",
      "U (oo)",
      "V (bay)",
      "W (do-bleh bay)",
      "X (eh-keys)",
      "Y (ih-gree-ay-gah)",
      "Z (say-tah)",
    ],
  },
  {
    id: "40",
    slug: "juli-slide-extended",
    title: "Juli Slide (Alphabet Extended)",
    description: "Learn the Spanish alphabet and vocabulary with each letter.",
    videoUrl: null,
    worksheetUrl: "/worksheets/Alphabet-Juli-Slide-Extended-Worksheet.pdf",
    audioUrl: "/audio/Juli-Slide-Extended.mp3",
    progress: 0,
    category: "Fundamentals",
    learningPoints: [
      "Spanish alphabet pronunciation",
      "Vocabulary associated with each letter",
      "Cultural and social justice vocabulary in Spanish",
    ],
    vocabularyWords: [
      "Abolicionista",
      "Ambiente",
      "Activista",
      "Bandera",
      "Boicot",
      "Cooperar",
      "Clima",
      "Discapacidad",
      "Español",
      "Feminista",
      "Humanidad",
      "Imaginación",
      "Justicia",
      "Liberación",
      "Migrante",
      "Naturalista",
      "Optimista",
      "Posible",
      "Revolución",
      "Sexualidad",
      "Transgenero",
      "Unión",
      "Visible",
      "Xenofobia",
      "Zapatista",
    ],
  },
]

// Function to get featured lessons for homepage
export function getFeaturedLessons(): Lesson[] {
  return [
    lessons.find((l) => l.slug === "alfabeto")!,
    lessons.find((l) => l.slug === "numeros")!,
    lessons.find((l) => l.slug === "colors-colores")!,
    lessons.find((l) => l.slug === "cuerpo")!,
    lessons.find((l) => l.slug === "juli-slide-alphabet")!,
    lessons.find((l) => l.slug === "espanoletry-adjectives")!,
  ].filter(Boolean)
}
