import type { Lesson } from "@/lib/types"

export const lessons: Lesson[] = [
  // Featured Video Lessons - The Big 4
  {
    id: "1",
    slug: "alfabeto",
    title: "Juli Slide (Spanish Alphabet)",
    description: "Learn the Spanish alphabet through hip hop music with proper pronunciation and letter recognition.",
    category: "Fundamentals",
    difficulty: "beginner",
    duration: "15 min",
    imageUrl: "/spanish-alphabet-lesson.png",
    videoUrl: "https://youtu.be/uOQMDaWSn6c",
    audioSrc: "/audio/Juli-Slide-Alphabet.mp3",
    vocabulary: [
      { spanish: "el alfabeto", english: "the alphabet" },
      { spanish: "las letras", english: "the letters" },
      { spanish: "A", english: "A" },
      { spanish: "B", english: "B" },
      { spanish: "C", english: "C" },
      { spanish: "D", english: "D" },
      { spanish: "E", english: "E" },
      { spanish: "F", english: "F" },
      { spanish: "G", english: "G" },
      { spanish: "H", english: "H" },
      { spanish: "I", english: "I" },
      { spanish: "J", english: "J" },
      { spanish: "K", english: "K" },
      { spanish: "L", english: "L" },
      { spanish: "M", english: "M" },
      { spanish: "N", english: "N" },
      { spanish: "Ñ", english: "Ñ" },
      { spanish: "O", english: "O" },
      { spanish: "P", english: "P" },
      { spanish: "Q", english: "Q" },
      { spanish: "R", english: "R" },
      { spanish: "S", english: "S" },
      { spanish: "T", english: "T" },
      { spanish: "U", english: "U" },
      { spanish: "V", english: "V" },
      { spanish: "W", english: "W" },
      { spanish: "X", english: "X" },
      { spanish: "Y", english: "Y" },
      { spanish: "Z", english: "Z" },
    ],
    objectives: [
      "Master Spanish alphabet pronunciation",
      "Recognize all 29 letters including Ñ",
      "Understand letter sounds and combinations",
      "Build foundation for Spanish spelling",
    ],
    worksheetUrl: "/worksheets/alfabeto",
  },
  {
    id: "2",
    slug: "colores",
    title: "Colores (Colors in Spanish)",
    description: "Master Spanish color vocabulary through engaging hip hop beats and memorable lyrics.",
    category: "Vocabulary",
    difficulty: "beginner",
    duration: "12 min",
    imageUrl: "/spanish-colors-rainbow-lesson.png",
    videoUrl: "https://www.youtube.com/watch?v=l0W4vdQKYbI",
    audioSrc: "/audio/lessons/colors-lesson.mp3",
    vocabulary: [
      { spanish: "verde", english: "green" },
      { spanish: "negro", english: "black" },
      { spanish: "azul", english: "blue" },
      { spanish: "blanco", english: "white" },
      { spanish: "morado", english: "purple" },
      { spanish: "anaranjado", english: "orange" },
      { spanish: "rojo", english: "red" },
      { spanish: "marrón", english: "brown" },
      { spanish: "amarillo", english: "yellow" },
      { spanish: "gris", english: "gray" },
      { spanish: "rosa", english: "pink" },
    ],
    objectives: [
      "Identify all basic colors in Spanish",
      "Use color adjectives correctly",
      "Describe objects using colors",
      "Understand color agreement with nouns",
    ],
    worksheetUrl: "/worksheets/colores",
  },
  {
    id: "3",
    slug: "numeros",
    title: "Numbers (0 to 101)",
    description: "Count and learn numbers in Spanish with rhythm and rhyme that makes learning fun and memorable.",
    category: "Numbers",
    difficulty: "beginner",
    duration: "18 min",
    imageUrl: "/spanish-numbers-lesson.png",
    videoUrl: "https://youtu.be/iVkolTR98ew",
    audioSrc: "/audio/lessons/numbers-0-101-song.mp3",
    vocabulary: [
      { spanish: "cero", english: "zero" },
      { spanish: "uno", english: "one" },
      { spanish: "dos", english: "two" },
      { spanish: "tres", english: "three" },
      { spanish: "cuatro", english: "four" },
      { spanish: "cinco", english: "five" },
      { spanish: "seis", english: "six" },
      { spanish: "siete", english: "seven" },
      { spanish: "ocho", english: "eight" },
      { spanish: "nueve", english: "nine" },
      { spanish: "diez", english: "ten" },
      { spanish: "veinte", english: "twenty" },
      { spanish: "treinta", english: "thirty" },
      { spanish: "cuarenta", english: "forty" },
      { spanish: "cincuenta", english: "fifty" },
      { spanish: "sesenta", english: "sixty" },
      { spanish: "setenta", english: "seventy" },
      { spanish: "ochenta", english: "eighty" },
      { spanish: "noventa", english: "ninety" },
      { spanish: "cien", english: "one hundred" },
      { spanish: "ciento uno", english: "one hundred one" },
    ],
    objectives: [
      "Count from 0 to 101 in Spanish",
      "Understand number patterns and rules",
      "Use numbers in daily conversations",
      "Master pronunciation of complex numbers",
    ],
    worksheetUrl: "/worksheets/numeros",
  },
  {
    id: "4",
    slug: "cuerpo",
    title: "Cuerpo (Body Parts)",
    description: "Learn Spanish vocabulary for body parts through engaging hip hop music and visual associations.",
    category: "Vocabulary",
    difficulty: "beginner",
    duration: "14 min",
    imageUrl: "/spanish-body-parts.png",
    videoUrl: "https://youtu.be/0KbRb6Qt34s",
    audioSrc: "/audio/lessons/body-parts-lesson.mp3",
    vocabulary: [
      { spanish: "cabeza", english: "head" },
      { spanish: "cara", english: "face" },
      { spanish: "ojos", english: "eyes" },
      { spanish: "nariz", english: "nose" },
      { spanish: "boca", english: "mouth" },
      { spanish: "dientes", english: "teeth" },
      { spanish: "cuello", english: "neck" },
      { spanish: "brazo", english: "arm" },
      { spanish: "mano", english: "hand" },
      { spanish: "dedos", english: "fingers" },
      { spanish: "pierna", english: "leg" },
      { spanish: "pie", english: "foot" },
      { spanish: "pelo", english: "hair" },
      { spanish: "barba", english: "beard" },
    ],
    objectives: [
      "Name all major body parts in Spanish",
      "Use possessive pronouns with body parts",
      "Describe physical appearance",
      "Build vocabulary for health conversations",
    ],
    worksheetUrl: "/worksheets/cuerpo",
  },

  // Audio-Only Lessons with Rich Content
  {
    id: "5",
    slug: "pronouns",
    title: "Subject & Object Pronouns (We Nosotros)",
    description: "Master Spanish pronouns with the catchy 'We Nosotros' song and comprehensive grammar explanations.",
    category: "Grammar",
    difficulty: "intermediate",
    duration: "18 min",
    imageUrl: "/spanish-pronouns-lesson.png",
    videoUrl: null,
    audioSrc: "/audio/lessons/pronouns-lesson.mp3",
    vocabulary: [
      { spanish: "yo", english: "I" },
      { spanish: "tú", english: "you (informal)" },
      { spanish: "él", english: "he" },
      { spanish: "ella", english: "she" },
      { spanish: "nosotros", english: "we" },
      { spanish: "vosotros", english: "you all (Spain)" },
      { spanish: "ellos", english: "they (masculine)" },
      { spanish: "ellas", english: "they (feminine)" },
      { spanish: "usted", english: "you (formal)" },
      { spanish: "me", english: "me" },
      { spanish: "te", english: "you" },
      { spanish: "lo", english: "him/it" },
      { spanish: "la", english: "her/it" },
      { spanish: "nos", english: "us" },
      { spanish: "los", english: "them (masculine)" },
      { spanish: "las", english: "them (feminine)" },
    ],
    objectives: [
      "Use subject pronouns correctly",
      "Understand direct and indirect object pronouns",
      "Apply pronouns in complex sentences",
      "Master formal vs informal address",
    ],
    worksheetUrl: "/worksheets/pronouns",
  },
  {
    id: "6",
    slug: "kankakee-places",
    title: "Kankakee (Places in the City)",
    description: "Explore vocabulary for places in a city or town with this engaging musical lesson.",
    category: "Places",
    difficulty: "beginner",
    duration: "13 min",
    imageUrl: "/spanish-city-neighborhood-lesson.png",
    videoUrl: null,
    audioSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Kankakee%20%28Places%29-GbMu0ElI9zdspOrxgMY2rbZtw8m98u.mp3",
    vocabulary: [
      { spanish: "la ciudad", english: "the city" },
      { spanish: "el pueblo", english: "the town" },
      { spanish: "la calle", english: "the street" },
      { spanish: "la tienda", english: "the store" },
      { spanish: "el restaurante", english: "the restaurant" },
      { spanish: "el parque", english: "the park" },
      { spanish: "la escuela", english: "the school" },
      { spanish: "la biblioteca", english: "the library" },
      { spanish: "el museo", english: "the museum" },
      { spanish: "el cine", english: "the cinema" },
      { spanish: "el supermercado", english: "the supermarket" },
      { spanish: "la estación", english: "the station" },
    ],
    objectives: [
      "Name common places in a city",
      "Give and ask for directions",
      "Describe your neighborhood",
      "Use prepositions with places",
    ],
    worksheetUrl: "/worksheets/places",
  },
  {
    id: "7",
    slug: "puff-lah",
    title: "Puff Lah (Essential Vocabulary)",
    description: "A fun hip-hop song to help you learn essential Spanish vocabulary with perfect rhythm and flow.",
    category: "Vocabulary",
    difficulty: "beginner",
    duration: "10 min",
    imageUrl: "/spanish-vocabulary-lesson.png",
    videoUrl: null,
    audioSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Puff%20Lah-I26hPJz9k2Yr7VGXt8khddYzxxXmkZ.mp3",
    vocabulary: [
      { spanish: "hola", english: "hello" },
      { spanish: "adiós", english: "goodbye" },
      { spanish: "gracias", english: "thank you" },
      { spanish: "por favor", english: "please" },
      { spanish: "sí", english: "yes" },
      { spanish: "no", english: "no" },
      { spanish: "buenos días", english: "good morning" },
      { spanish: "buenas noches", english: "good night" },
      { spanish: "perdón", english: "excuse me" },
      { spanish: "lo siento", english: "I'm sorry" },
    ],
    objectives: [
      "Master essential Spanish greetings",
      "Use polite expressions correctly",
      "Build confidence in basic conversations",
      "Understand cultural context of expressions",
    ],
    worksheetUrl: "/worksheets/essential-vocabulary",
  },
  {
    id: "8",
    slug: "spa-nish-travel",
    title: "Spa Nish (Travel Vocabulary)",
    description: "Essential Spanish vocabulary for travelers through catchy hip-hop beats and memorable phrases.",
    category: "Travel",
    difficulty: "beginner",
    duration: "13 min",
    imageUrl: "/spanish-travel-lesson.png",
    videoUrl: null,
    audioSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Spa%20Nish%20%28Travel%29-MneSoE1IMEWKgfDJRGlHq7Hm5hfeCm.mp3",
    vocabulary: [
      { spanish: "el viaje", english: "the trip" },
      { spanish: "el hotel", english: "the hotel" },
      { spanish: "el aeropuerto", english: "the airport" },
      { spanish: "el pasaporte", english: "the passport" },
      { spanish: "la maleta", english: "the suitcase" },
      { spanish: "el boleto", english: "the ticket" },
      { spanish: "la reservación", english: "the reservation" },
      { spanish: "el turista", english: "the tourist" },
      { spanish: "la playa", english: "the beach" },
      { spanish: "la montaña", english: "the mountain" },
      { spanish: "el mapa", english: "the map" },
      { spanish: "la dirección", english: "the address" },
    ],
    objectives: [
      "Navigate travel situations in Spanish",
      "Make hotel reservations",
      "Ask for directions while traveling",
      "Handle airport and transportation vocabulary",
    ],
    worksheetUrl: "/worksheets/travel",
  },
  {
    id: "9",
    slug: "the-docs-health",
    title: "The Docs (Health & Medical)",
    description: "Learn health and medical vocabulary in Spanish through engaging music and practical scenarios.",
    category: "Health",
    difficulty: "intermediate",
    duration: "16 min",
    imageUrl: "/spanish-health-lesson.png",
    videoUrl: null,
    audioSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/The%20Docs%20%28Health%29-5glsdi4N7kU8cqrwmI0CkUkMqWJyNk.mp3",
    vocabulary: [
      { spanish: "el doctor", english: "the doctor" },
      { spanish: "la doctora", english: "the female doctor" },
      { spanish: "el hospital", english: "the hospital" },
      { spanish: "la enfermedad", english: "the illness" },
      { spanish: "el dolor", english: "the pain" },
      { spanish: "la medicina", english: "the medicine" },
      { spanish: "la receta", english: "the prescription" },
      { spanish: "la farmacia", english: "the pharmacy" },
      { spanish: "enfermo", english: "sick" },
      { spanish: "sano", english: "healthy" },
      { spanish: "la fiebre", english: "the fever" },
      { spanish: "la tos", english: "the cough" },
    ],
    objectives: [
      "Describe symptoms and health problems",
      "Communicate with healthcare providers",
      "Understand medical instructions",
      "Navigate pharmacy and hospital visits",
    ],
    worksheetUrl: "/worksheets/health",
  },
  {
    id: "10",
    slug: "i-look-good",
    title: "I Look Good (Me Parece Guapo)",
    description: "Learn appearance and description vocabulary in Spanish through upbeat music and self-expression.",
    category: "Descriptions",
    difficulty: "beginner",
    duration: "12 min",
    imageUrl: "/spanish-appearance-lesson.png",
    videoUrl: null,
    audioSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/I%20Look%20Good%20%28Me%20Parece%20Guapo%29-UXYICdXPrOKgDFGV5dCe7dYinVmkoL.mp3",
    vocabulary: [
      { spanish: "guapo", english: "handsome" },
      { spanish: "guapa", english: "beautiful" },
      { spanish: "bonito", english: "pretty" },
      { spanish: "alto", english: "tall" },
      { spanish: "bajo", english: "short" },
      { spanish: "delgado", english: "thin" },
      { spanish: "gordo", english: "fat" },
      { spanish: "fuerte", english: "strong" },
      { spanish: "me parece", english: "I think/it seems to me" },
      { spanish: "se ve", english: "it looks" },
      { spanish: "joven", english: "young" },
      { spanish: "viejo", english: "old" },
    ],
    objectives: [
      "Describe physical appearance",
      "Express opinions about looks",
      "Use 'parecer' and 'verse' correctly",
      "Build confidence in self-description",
    ],
    worksheetUrl: "/worksheets/appearance",
  },
  {
    id: "11",
    slug: "bored-in-the-house",
    title: "Bored in the House (House & Home)",
    description: "Learn vocabulary for rooms and items in a house through relatable music about home life.",
    category: "Home",
    difficulty: "beginner",
    duration: "11 min",
    imageUrl: "/spanish-rooms-furniture-house-lesson.png",
    videoUrl: null,
    audioSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bored%20in%20the%20House%20%28House%29-Lb20Mso2SfpwvUicWAXkwL711bUwbw.mp3",
    vocabulary: [
      { spanish: "la casa", english: "the house" },
      { spanish: "la sala", english: "the living room" },
      { spanish: "la cocina", english: "the kitchen" },
      { spanish: "el dormitorio", english: "the bedroom" },
      { spanish: "el baño", english: "the bathroom" },
      { spanish: "el comedor", english: "the dining room" },
      { spanish: "la mesa", english: "the table" },
      { spanish: "la silla", english: "the chair" },
      { spanish: "la cama", english: "the bed" },
      { spanish: "el sofá", english: "the sofa" },
      { spanish: "la televisión", english: "the television" },
      { spanish: "la ventana", english: "the window" },
      { spanish: "la puerta", english: "the door" },
    ],
    objectives: [
      "Name all rooms in a house",
      "Describe furniture and household items",
      "Talk about activities at home",
      "Use prepositions with house vocabulary",
    ],
    worksheetUrl: "/worksheets/house",
  },
  {
    id: "12",
    slug: "espanoletry-adjectives",
    title: "Españoletry (Spanish Adjectives)",
    description: "Master Spanish adjectives through music and rhythm, learning agreement and placement rules.",
    category: "Grammar",
    difficulty: "beginner",
    duration: "14 min",
    imageUrl: "/spanish-personality-adjectives.png",
    videoUrl: null,
    audioSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Espan%CC%83oletry%20%28Adjectives%29-rlBulUTAaAq2fvPnX9XslgoeZQ3uDq.mp3",
    vocabulary: [
      { spanish: "grande", english: "big" },
      { spanish: "pequeño", english: "small" },
      { spanish: "bueno", english: "good" },
      { spanish: "malo", english: "bad" },
      { spanish: "feliz", english: "happy" },
      { spanish: "triste", english: "sad" },
      { spanish: "rápido", english: "fast" },
      { spanish: "lento", english: "slow" },
      { spanish: "nuevo", english: "new" },
      { spanish: "viejo", english: "old" },
      { spanish: "interesante", english: "interesting" },
      { spanish: "aburrido", english: "boring" },
    ],
    objectives: [
      "Use common Spanish adjectives correctly",
      "Understand adjective agreement rules",
      "Master adjective placement in sentences",
      "Describe people, places, and things",
    ],
    worksheetUrl: "/worksheets/adjectives",
  },
  {
    id: "13",
    slug: "book-dun-classroom",
    title: "Book Dun (Classroom & Education)",
    description: "Learn vocabulary for classroom objects and activities through educational hip-hop music.",
    category: "Education",
    difficulty: "beginner",
    duration: "15 min",
    imageUrl: "/spanish-classroom-lesson.png",
    videoUrl: null,
    audioSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Book%20Dun%20%28Classroom%29-mGAq4h8MoWDTCpbjcBDghagS2V1iYH.mp3",
    vocabulary: [
      { spanish: "la clase", english: "the class" },
      { spanish: "el estudiante", english: "the student" },
      { spanish: "la estudiante", english: "the female student" },
      { spanish: "el maestro", english: "the teacher" },
      { spanish: "la maestra", english: "the female teacher" },
      { spanish: "el libro", english: "the book" },
      { spanish: "el cuaderno", english: "the notebook" },
      { spanish: "el lápiz", english: "the pencil" },
      { spanish: "la pluma", english: "the pen" },
      { spanish: "la mochila", english: "the backpack" },
      { spanish: "la pizarra", english: "the blackboard" },
      { spanish: "la tarea", english: "the homework" },
      { spanish: "el examen", english: "the exam" },
    ],
    objectives: [
      "Name classroom objects and supplies",
      "Understand school-related activities",
      "Use education vocabulary in context",
      "Follow classroom commands in Spanish",
    ],
    worksheetUrl: "/worksheets/classroom",
  },
  {
    id: "14",
    slug: "and-teach-clothing-jobs",
    title: "And Teach (Clothing & Jobs)",
    description: "Learn vocabulary for clothing items and professions through engaging musical instruction.",
    category: "Vocabulary",
    difficulty: "beginner",
    duration: "12 min",
    imageUrl: "/spanish-clothing-jobs-lesson.png",
    videoUrl: null,
    audioSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/And%20Teach%20%28Clothing_Jobs%29-uPy5rlMhaRU6zUVs0jeKn87NTNrNjn.mp3",
    vocabulary: [
      { spanish: "la ropa", english: "the clothes" },
      { spanish: "la camisa", english: "the shirt" },
      { spanish: "los pantalones", english: "the pants" },
      { spanish: "el vestido", english: "the dress" },
      { spanish: "los zapatos", english: "the shoes" },
      { spanish: "el trabajo", english: "the job" },
      { spanish: "el profesor", english: "the male teacher" },
      { spanish: "la profesora", english: "the female teacher" },
      { spanish: "el doctor", english: "the male doctor" },
      { spanish: "la doctora", english: "the female doctor" },
      { spanish: "el abogado", english: "the male lawyer" },
      { spanish: "la abogada", english: "the female lawyer" },
      { spanish: "el ingeniero", english: "the male engineer" },
      { spanish: "la ingeniera", english: "the female engineer" },
      { spanish: "el artista", english: "the male artist" },
      { spanish: "la artista", english: "the female artist" },
    ],
    objectives: [
      "Name common clothing items",
      "Describe different professions",
      "Understand gender agreement with jobs",
      "Talk about what people wear and do",
    ],
    worksheetUrl: "/worksheets/clothing-jobs",
  },

  // Additional Comprehensive Lessons
  {
    id: "15",
    slug: "time-telling",
    title: "Time Ain't Hard to Tell (Telling Time)",
    description: "Master telling time in Spanish through rhythmic music and practical examples.",
    category: "Time",
    difficulty: "beginner",
    duration: "16 min",
    imageUrl: "/spanish-telling-time.png",
    videoUrl: null,
    audioSrc: "/audio/Time-Aint-Hard-to-Tell.mp3",
    vocabulary: [
      { spanish: "la hora", english: "the time" },
      { spanish: "es la una", english: "it's one o'clock" },
      { spanish: "son las", english: "it's (for 2-12)" },
      { spanish: "y cuarto", english: "quarter past" },
      { spanish: "y media", english: "half past" },
      { spanish: "menos cuarto", english: "quarter to" },
      { spanish: "de la mañana", english: "in the morning" },
      { spanish: "de la tarde", english: "in the afternoon" },
      { spanish: "de la noche", english: "at night" },
      { spanish: "mediodía", english: "noon" },
      { spanish: "medianoche", english: "midnight" },
    ],
    objectives: [
      "Tell time accurately in Spanish",
      "Use time expressions correctly",
      "Distinguish between AM and PM",
      "Schedule activities using time vocabulary",
    ],
    worksheetUrl: "/worksheets/time",
  },
  {
    id: "16",
    slug: "weather-seasons",
    title: "¿Qué Tiempo Hace? (Weather & Seasons)",
    description: "Learn to talk about weather and seasons in Spanish through engaging musical instruction.",
    category: "Weather",
    difficulty: "beginner",
    duration: "13 min",
    imageUrl: "/spanish-weather-seasons.png",
    videoUrl: null,
    audioSrc: "/audio/Que-Tiempo-Hace-Weather.mp3",
    vocabulary: [
      { spanish: "el tiempo", english: "the weather" },
      { spanish: "hace calor", english: "it's hot" },
      { spanish: "hace frío", english: "it's cold" },
      { spanish: "llueve", english: "it rains" },
      { spanish: "nieva", english: "it snows" },
      { spanish: "hace viento", english: "it's windy" },
      { spanish: "hace sol", english: "it's sunny" },
      { spanish: "está nublado", english: "it's cloudy" },
      { spanish: "la primavera", english: "spring" },
      { spanish: "el verano", english: "summer" },
      { spanish: "el otoño", english: "autumn" },
      { spanish: "el invierno", english: "winter" },
    ],
    objectives: [
      "Describe weather conditions",
      "Name all four seasons",
      "Have weather conversations",
      "Plan activities based on weather",
    ],
    worksheetUrl: "/worksheets/weather",
  },
  {
    id: "17",
    slug: "family-members",
    title: "Talkin' Family (Family Members)",
    description: "Comprehensive vocabulary for family members and relationships in Spanish through music.",
    category: "Family",
    difficulty: "intermediate",
    duration: "17 min",
    imageUrl: "/spanish-family-members.png",
    videoUrl: null,
    audioSrc: "/audio/Talkin-Family-Extended-2.mp3",
    vocabulary: [
      { spanish: "la familia", english: "the family" },
      { spanish: "los padres", english: "the parents" },
      { spanish: "la madre", english: "the mother" },
      { spanish: "el padre", english: "the father" },
      { spanish: "la hermana", english: "the sister" },
      { spanish: "el hermano", english: "the brother" },
      { spanish: "la hija", english: "the daughter" },
      { spanish: "el hijo", english: "the son" },
      { spanish: "la abuela", english: "the grandmother" },
      { spanish: "el abuelo", english: "the grandfather" },
      { spanish: "la tía", english: "the aunt" },
      { spanish: "el tío", english: "the uncle" },
      { spanish: "la prima", english: "the female cousin" },
      { spanish: "el primo", english: "the male cousin" },
      { spanish: "la sobrina", english: "the niece" },
      { spanish: "el sobrino", english: "the nephew" },
    ],
    objectives: [
      "Name immediate and extended family",
      "Describe family relationships",
      "Talk about your family in Spanish",
      "Use possessive adjectives with family",
    ],
    worksheetUrl: "/worksheets/family",
  },
  {
    id: "18",
    slug: "food-meals",
    title: "Time to Eat (Ya Comí - Food & Meals)",
    description: "Learn Spanish vocabulary for food, meals, and dining through delicious musical content.",
    category: "Food",
    difficulty: "beginner",
    duration: "18 min",
    imageUrl: "/spanish-food-lesson.png",
    videoUrl: null,
    audioSrc: "/audio/lessons/food-meals-lesson.mp3",
    vocabulary: [
      { spanish: "la comida", english: "the food" },
      { spanish: "el desayuno", english: "breakfast" },
      { spanish: "el almuerzo", english: "lunch" },
      { spanish: "la cena", english: "dinner" },
      { spanish: "las frutas", english: "fruits" },
      { spanish: "las verduras", english: "vegetables" },
      { spanish: "la carne", english: "meat" },
      { spanish: "el pollo", english: "chicken" },
      { spanish: "el pescado", english: "fish" },
      { spanish: "el arroz", english: "rice" },
      { spanish: "el pan", english: "bread" },
      { spanish: "la leche", english: "milk" },
      { spanish: "el agua", english: "water" },
      { spanish: "el jugo", english: "juice" },
    ],
    objectives: [
      "Name foods and meals in Spanish",
      "Order food at restaurants",
      "Describe food preferences",
      "Understand cooking vocabulary",
    ],
    worksheetUrl: "/worksheets/food",
  },
]

export const categories = [
  "Fundamentals",
  "Vocabulary",
  "Numbers",
  "Grammar",
  "Places",
  "Travel",
  "Health",
  "Descriptions",
  "Home",
  "Education",
  "Time",
  "Weather",
  "Family",
  "Food",
]

// Function to get featured lessons for homepage
export function getFeaturedLessons(): Lesson[] {
  return [
    lessons.find((l) => l.slug === "alfabeto")!,
    lessons.find((l) => l.slug === "colores")!,
    lessons.find((l) => l.slug === "numeros")!,
    lessons.find((l) => l.slug === "cuerpo")!,
  ].filter(Boolean)
}

// Function to get video lessons
export function getVideoLessons(): Lesson[] {
  return lessons.filter((lesson) => lesson.videoUrl && lesson.videoUrl.trim() !== "")
}

// Function to get audio lessons
export function getAudioLessons(): Lesson[] {
  return lessons.filter((lesson) => lesson.audioSrc && lesson.audioSrc.trim() !== "")
}

// Function to get lessons with worksheets
export function getWorksheetLessons(): Lesson[] {
  return lessons.filter(
    (lesson) => lesson.worksheetUrl && lesson.worksheetUrl.trim() !== "" && lesson.worksheetUrl !== "#",
  )
}
