export const mockContestEntries = [
  {
    id: "entry-1",
    name: "Miguel Rodriguez",
    email: "miguel@example.com",
    schoolName: "Washington High School",
    entryType: "individual",
    songTitle: "Números en Ritmo",
    description: "A song about counting in Spanish with a hip hop beat. I used the numbers 1-10 and created a catchy hook.",
    spanishWords: "uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez",
    audioFileUrl: "/audio/sample-word.mp3",
    submittedAt: "2025-05-15T14:30:00Z",
    votes: 24,
    isWinner: true
  },
  {
    id: "entry-2",
    name: "Sofia Chen",
    email: "sofia@example.com",
    schoolName: "Lincoln Middle School",
    entryType: "individual",
    songTitle: "Colores del Mundo",
    description: "My song is about colors in Spanish. I created a beat using GarageBand and recorded my vocals over it.",
    spanishWords: "rojo, azul, verde, amarillo, morado",
    audioFileUrl: "/audio/sample-word.mp3",
    submittedAt: "2025-05-16T09:15:00Z",
    votes: 18,
    isWinner: false
  },
  {
    id: "entry-3",
    name: "Ms. Garcia's Spanish Class",
    email: "garcia@example.com",
    schoolName: "Oakwood Elementary",
    entryType: "class",
    songTitle: "La Familia Grande",
    description: "Our class created a song about family members in Spanish. Each student contributed a line about a different family member.",
    spanishWords: "madre, padre, hermano, hermana, abuelo, abuela, tío, tía, primo, prima, sobrino, sobrina, hijo, hija, esposo, esposa",
    audioFileUrl: "/audio/sample-word.mp3",
    submittedAt: "2025-05-17T13:45:00Z",
    votes: 42,
    isWinner: true
  },
  {
    id: "entry-4",
    name: "Jamal Washington",
    email: "jamal@example.com",
    schoolName: "Roosevelt High School",
    entryType: "individual",
    songTitle: "El Tiempo y Las Estaciones",
    description: "A song about weather and seasons in Spanish. I used a trap beat and incorporated vocabulary about the four seasons.",
    spanishWords: "primavera, verano, otoño, invierno, sol, lluvia, nieve, calor, frío",
    audioFileUrl: "/audio/sample-word.mp3",
    submittedAt: "2025-05-18T16:20:00Z",
    votes: 15,
    isWinner: false
  },
  {
    id: "entry-5",
    name: "Mr. Johnson's 5th Period",
    email: "johnson@example.com",
    schoolName: "Central Middle School",
    entryType: "class",
    songTitle: "En Mi Barrio",
    description: "Our class created a song about places in the neighborhood. We used a boom bap beat and each student rapped about a different location.",
    spanishWords: "escuela, parque, biblioteca, tienda, restaurante, cine, hospital, banco, iglesia, estación, mercado, panadería, carnicería, farmacia",
    audioFileUrl: "/audio/sample-word.mp3",
    submittedAt: "2025-05-19T10:30:00Z",
    votes: 37,
    isWinner: false
  },
  {
    id: "entry-6",
    name: "Aisha Patel",
    email: "aisha@example.com",
    schoolName: "Westside Academy",
    entryType: "individual",
    songTitle: "Mi Cuerpo en Movimiento",
    description: "A song about body parts in Spanish with a dance routine. I created a reggaeton-inspired beat and incorporated movement instructions.",
    spanishWords: "cabeza, hombros, rodillas, pies, ojos, orejas, boca, nariz",
    audioFileUrl: "/audio/sample-word.mp3",
    submittedAt: "2025-05-20T14:15:00Z",
    votes: 29,
    isWinner: false
  }
]
